meta:
  version: 1.0
  environment: python
  toolchain:
    name: docker
    type: docker

services:
  web:
    image: python:3.11-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80
    env:
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,.amvera.ru,.amvera.io,*"
      DATABASE_URL: ""