meta:
  version: 1.0
  toolchain:
    name: docker
    type: docker

services:
  web:
    image: python:3.11-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    env:
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,.amvera.ru,.amvera.io"

  db:
    image: postgres:16
    env:
      POSTGRES_DB: neondriver
      POSTGRES_USER: neondriver
      POSTGRES_PASSWORD: neondriver
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432